### ISSUE TITLE
Type of MinGLColor.rgba

### ISSUE THREAD

**Issue by tbeu** [amengol/MinGL#1]
In https://github.com/amengol/MinGL/blob/b2cc34cd2f92088a329683d7479a73ac69f4626c/Example/Main.cpp#L54 the color values are initilaized by floats whereas the type requires uint8. What should be the correct type to be used?

Edit: Only float actually works.

**Comment by amengol** [comment]
That was an overlook, but there's an implicitly conversion there. It would be more elegant/correct to initialize it with int literals.
I'll correct in the next commit.

**Comment by amengol** [comment]
Actually, type of rgba should be float all along. I've just corrected that.
